More improvments

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -22,13 +22,34 @@ before_script:
 cache:
   paths:
     - .conan
+    
+# macOS Build Stage (if enabled)
+# macos_build:
+#   stage: build
+#   tags:
+#     - dc-zone
+#   image: apple/Xcode:latest
+#   script:
+#     - |
+#       rm -rf $PROJECT_NAME  # Clean up previous clone if any
+#       git clone https://gitlab.esss.lu.se/ecdc/ess-dmsc/conan-epics.git
+#       cd $PROJECT_NAME
+#       git checkout $CI_COMMIT_REF_NAME
 
+#       # macOS: Package
+#       conan create . ${CONAN_USER}/${CONAN_PKG_CHANNEL} --build=outdated
+#   only:
+#     - master
+#   artifacts:
+#     paths:
+#       - build/
+#     expire_in: 1 day
 
-# Archiving - Install Stage
-installing:
-  stage: install
+# Archiving Build Node
+archiving:
+  stage: archive
   tags:
-    - dc-zone
+    - dc-zone 
     - docker
   image: registry.esss.lu.se/ecdc/ess-dmsc/docker-centos7-build-node:12.3.0
   script:
@@ -57,57 +78,39 @@ installing:
         # TODO: ensuring build packages Conan operations
         conan install .. --build=epics
 
-      EOF
-  artifacts:
-    paths:
-      - archiving/epics/
-    expire_in: 1 day
-
-
-# macOS Build Stage (if enabled)
-# macos_build:
-#   stage: build
-#   tags:
-#     - dc-zone
-#   image: apple/Xcode:latest
-#   script:
-#     - |
-#       rm -rf $PROJECT_NAME  # Clean up previous clone if any
-#       git clone https://gitlab.esss.lu.se/ecdc/ess-dmsc/conan-epics.git
-#       cd $PROJECT_NAME
-#       git checkout $CI_COMMIT_REF_NAME
-
-#       # macOS: Package
-#       conan create . ${CONAN_USER}/${CONAN_PKG_CHANNEL} --build=outdated
-#   only:
-#     - master
-#   artifacts:
-#     paths:
-#       - build/
-#     expire_in: 1 day
-
-
-# Archiving - Archive Stage
-archiving:
-  stage: archive
-  tags:
-    - dc-zone
-    - docker
-  image: registry.esss.lu.se/ecdc/ess-dmsc/docker-centos7-build-node:12.3.0
-  script:
-    - echo "Archiving..."
-    - |
-      scl enable devtoolset-11 rh-python38 -- /bin/bash -e -x <<EOF
-        cd archiving/epics
+        echo "Archiving..."
 
         # TODO: REMOVE: ensuring that package exist
         conan search epics/7.0.6@"${CONAN_USER}"/"${CONAN_PKG_CHANNEL}" -r=ecdc-conan-release --table=table.html
         conan remote list
         #conan remote update ecdc-conan-release <new-url>
 
-
         # TODO: Conan upload test
         # Set ${conanUploadFlag}
+
+        # Inspect local package
+        local_options=\$(conan inspect --raw options epics/7.0.6@"${CONAN_USER}"/"${CONAN_PKG_CHANNEL}")
+        local_settings=\$(conan inspect --raw settings epics/7.0.6@"${CONAN_USER}"/"${CONAN_PKG_CHANNEL}")
+
+        # Fetch remote package info
+        conan search epics/7.0.6@"${CONAN_USER}"/"${CONAN_PKG_CHANNEL}" -r=ecdc-conan-release --json=remote_info.json || {
+          echo "Remote package not found. Uploading..."
+          conan upload --no-overwrite --remote ecdc-conan-release epics/7.0.6@"${CONAN_USER}"/"${CONAN_PKG_CHANNEL}"
+          exit 0
+        }
+
+        # Parse and compare
+        remote_options=\$(jq -r '.results[0].options' remote_info.json)
+        remote_settings=\$(jq -r '.results[0].settings' remote_info.json)
+
+        if [[ "\$local_options" != "\$remote_options" || "\$local_settings" != "\$remote_settings" ]]; then
+          echo "UPLOAD!""
+          #echo "Differences found between local and remote packages. Uploading..."
+          #conan upload --no-overwrite --remote ecdc-conan-release epics/7.0.6@"${CONAN_USER}"/"${CONAN_PKG_CHANNEL}"
+        else
+          echo "No differences found. Skipping upload."
+        fi
+
         conan upload --no-overwrite --remote ecdc-conan-release epics/7.0.6@"${CONAN_USER}"/"${CONAN_PKG_CHANNEL}"
 
         # Stage Archive
@@ -122,6 +125,7 @@ archiving:
         cd ..
         tar czvf ../epics.tar.gz epics
       EOF
+
   artifacts:
     paths:
       - epics.tar.gz
