Commenting out testing

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -40,11 +40,11 @@ container_build_node:
         mkdir epics
         cd epics
         conan create .. ${CONAN_USER}/${CONAN_PKG_CHANNEL} --build=outdated
-        conan search epics/7.0.6@${CONAN_USER}/${CONAN_PKG_CHANNEL} -r=ecdc-conan-external --json=remote_info.json || {
-          echo 'Remote package not found. Uploading...'
-          conan upload --no-overwrite --remote ecdc-conan-external epics/7.0.6@${CONAN_USER}/${CONAN_PKG_CHANNEL} --all
-          exit 0
-        }
+        # conan search epics/7.0.6@${CONAN_USER}/${CONAN_PKG_CHANNEL} -r=ecdc-conan-external --json=remote_info.json || {
+        #   echo 'Remote package not found. Uploading...'
+        #   conan upload --no-overwrite --remote ecdc-conan-external epics/7.0.6@${CONAN_USER}/${CONAN_PKG_CHANNEL} --all
+        #   exit 0
+        # }
         echo "Archiving build artifacts..."
         pwd
         ls
