Not yet right

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -54,8 +54,8 @@ archiving:
   script: |
     echo "Installing dependencies..."
     # Install Python 3.8 if it's not already installed
-    if ! command -v python3 &> /dev/null; then
-      echo "Python 3 not found, installing Python 3.8..."
+    if ! command -v python3.8 &> /dev/null; then
+      echo "Python 3.8 not found, installing Python 3.8..."
       yum -y groupinstall "Development Tools"
       yum -y install gcc
       yum -y install https://centos7.iuscommunity.org/ius-release.rpm
@@ -63,9 +63,11 @@ archiving:
       alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1
       alternatives --set python3 /usr/bin/python3.8
     fi
+    
     # Install pip for Python 3.8
     curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
-    python3 get-pip.py
+    python3.8 get-pip.py
+
     # Install Conan
     pip install conan
     pwd
